import React, { useState, useEffect } from 'react';
import { api } from '../api';
import { useAuth } from '../components/AuthContext';

export default function HiringManagerPage() {
  const { user } = useAuth();
  const [certifiedJobs, setCertifiedJobs] = useState([]);
  const [selectedJob, setSelectedJob] = useState(null);
  const [candidates, setCandidates] = useState([]);
  const [certification, setCertification] = useState(null);
  const [decision, setDecision] = useState(null);
  const [selectedCandidate, setSelectedCandidate] = useState('');
  const [alternates, setAlternates] = useState([]);
  const [notes, setNotes] = useState('');
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [toast, setToast] = useState(null);

  useEffect(() => {
    api.getCertifiedJobs().then(setCertifiedJobs).catch(console.error).finally(() => setLoading(false));
  }, []);

  const showToast = (msg, type = 'success') => {
    setToast({ msg, type });
    setTimeout(() => setToast(null), 4000);
  };

  const loadJob = async (jobId) => {
    setLoading(true);
    try {
      const data = await api.getHMCandidates(jobId);
      setCandidates(data.candidates || []);
      setCertification(data.certification);
      setDecision(data.decision);
      setSelectedJob(jobId);
      if (data.decision) {
        setSelectedCandidate(data.decision.selected_candidate_id || '');
        try { setAlternates(JSON.parse(data.decision.alternates || '[]')); } catch { setAlternates([]); }
        setNotes(data.decision.notes || '');
      } else {
        setSelectedCandidate('');
        setAlternates([]);
        setNotes('');
      }
    } catch (err) { showToast(err.message, 'error'); }
    finally { setLoading(false); }
  };

  const toggleAlternate = (candidateId) => {
    if (candidateId === selectedCandidate) return; // can't be both
    setAlternates(prev => prev.includes(candidateId) ? prev.filter(id => id !== candidateId) : [...prev, candidateId]);
  };

  const handleSubmit = async () => {
    if (!selectedCandidate) return showToast('Please select a candidate first', 'error');
    if (!confirm('Submit your hiring decision? This will be recorded in the audit log.')) return;
    setSubmitting(true);
    try {
      await api.submitHiringDecision({ job_id: selectedJob, selected_candidate_id: selectedCandidate, alternates, notes });
      showToast('Hiring decision submitted successfully');
      loadJob(selectedJob);
    } catch (err) { showToast(err.message, 'error'); }
    finally { setSubmitting(false); }
  };

  const getStatusClass = (q) => {
    if (q?.includes('Meets') && !q?.includes('Partially')) return 'status-meets';
    if (q?.includes('Partially')) return 'status-partial';
    return 'status-not';
  };

  return (
    <div>
      <div className="page-header">
        <h2>Hiring Manager Portal</h2>
        <p>Review certified candidates and make your selection. Only positions certified by an HR Recruiter are visible.</p>
      </div>

      {/* EU AI Act transparency notice */}
      <div style={{ padding: '10px 16px', marginBottom: 16, background: 'var(--accent-soft)', borderRadius: 'var(--radius-sm)', fontSize: 12, color: 'var(--accent)', border: '1px solid var(--accent)' }}>
        <strong>AI Transparency Notice (EU AI Act / NYC LL144):</strong> Candidate scores were generated by an AI system (Anthropic Claude) evaluating only job-related criteria. All results have been reviewed and certified by an HR specialist before being made available to you.
      </div>

      {/* Job selector */}
      {!selectedJob ? (
        <div className="card">
          <div className="card-header"><h3>Certified Positions</h3></div>
          {loading ? (
            <div style={{ textAlign: 'center', padding: 40 }}><div className="spinner" style={{ margin: '0 auto' }} /></div>
          ) : certifiedJobs.length === 0 ? (
            <div className="empty-state">
              <div className="icon">🔒</div>
              <h3>No certified positions</h3>
              <p>Positions will appear here after an HR Recruiter certifies the candidate review.</p>
            </div>
          ) : (
            <div className="table-wrap">
              <table>
                <thead><tr><th>Position</th><th>Certified By</th><th>Certified Date</th><th>Qualified Candidates</th><th>Decision</th><th></th></tr></thead>
                <tbody>
                  {certifiedJobs.map(j => (
                    <tr key={j.id}>
                      <td style={{ fontWeight: 600, color: 'var(--text-primary)' }}>{j.title}</td>
                      <td style={{ fontSize: 12 }}>{j.certified_by_name}</td>
                      <td style={{ fontSize: 12 }}>{new Date(j.certified_at).toLocaleDateString()}</td>
                      <td style={{ fontFamily: 'var(--font-mono)', fontWeight: 600 }}>{j.qualified_count}</td>
                      <td>{j.has_decision > 0 ? <span style={{ color: 'var(--green)', fontWeight: 600, fontSize: 11 }}>Submitted</span> : <span style={{ color: 'var(--yellow)', fontSize: 11 }}>Pending</span>}</td>
                      <td><button className="btn btn-primary btn-sm" onClick={() => loadJob(j.id)}>Review</button></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      ) : (
        <>
          {/* Back button */}
          <button className="btn btn-secondary" onClick={() => { setSelectedJob(null); setCandidates([]); }} style={{ marginBottom: 16, fontSize: 12 }}>
            ← Back to all positions
          </button>

          {/* Certification info */}
          {certification && (
            <div style={{ marginBottom: 16, padding: 14, background: 'var(--green-soft)', borderRadius: 'var(--radius-sm)', border: '1px solid var(--green)', fontSize: 12 }}>
              <strong style={{ color: 'var(--green)' }}>Certified</strong> by {certification.certified_by_name} on {new Date(certification.certified_at).toLocaleString()} · {certification.candidates_reviewed} candidates reviewed
            </div>
          )}

          {/* Existing decision */}
          {decision && (
            <div className="card" style={{ marginBottom: 16, borderLeft: '4px solid var(--green)' }}>
              <div className="card-header"><h3>Current Decision</h3></div>
              <p style={{ fontSize: 13 }}>
                <strong>Selected:</strong> {candidates.find(c => c.candidate_id === decision.selected_candidate_id)?.original_filename || decision.selected_candidate_id}
              </p>
              {(() => { try { const alts = JSON.parse(decision.alternates || '[]'); return alts.length > 0 ? <p style={{ fontSize: 13 }}><strong>Alternates:</strong> {alts.map(a => candidates.find(c => c.candidate_id === a)?.original_filename || a).join(', ')}</p> : null; } catch { return null; } })()}
              {decision.notes && <p style={{ fontSize: 12, color: 'var(--text-muted)' }}>Notes: {decision.notes}</p>}
              <p style={{ fontSize: 11, color: 'var(--text-muted)' }}>Submitted {new Date(decision.created_at).toLocaleString()} by {decision.hiring_manager_email}</p>
            </div>
          )}

          {/* Candidate list */}
          <div className="card">
            <div className="card-header">
              <h3>Qualified Candidates ({candidates.length})</h3>
              <span className="ai-label">AI-Assisted • Human Certified</span>
            </div>

            {candidates.length === 0 ? (
              <div className="empty-state"><div className="icon">📋</div><h3>No qualified candidates</h3></div>
            ) : (
              <div className="table-wrap">
                <table>
                  <thead>
                    <tr><th>Select</th><th>Alternate</th><th>Candidate</th><th>Qualification</th><th>Score</th><th>Skills</th><th>Experience</th><th>Education</th></tr>
                  </thead>
                  <tbody>
                    {candidates.map(c => (
                      <tr key={c.id} style={{ background: selectedCandidate === c.candidate_id ? 'var(--green-soft)' : alternates.includes(c.candidate_id) ? 'var(--accent-soft)' : undefined }}>
                        <td>
                          <input
                            type="radio"
                            name="selected"
                            checked={selectedCandidate === c.candidate_id}
                            onChange={() => { setSelectedCandidate(c.candidate_id); setAlternates(prev => prev.filter(a => a !== c.candidate_id)); }}
                          />
                        </td>
                        <td>
                          <input
                            type="checkbox"
                            checked={alternates.includes(c.candidate_id)}
                            disabled={selectedCandidate === c.candidate_id}
                            onChange={() => toggleAlternate(c.candidate_id)}
                          />
                        </td>
                        <td style={{ fontWeight: 500, color: 'var(--text-primary)' }}>{c.original_filename || 'Candidate'}</td>
                        <td><span className={`status-badge ${getStatusClass(c.qualification)}`}>{c.qualification}</span></td>
                        <td><span style={{ fontFamily: 'var(--font-mono)', fontWeight: 600 }}>{(c.overall_score || 0).toFixed(1)}<span style={{ color: 'var(--text-muted)', fontWeight: 400 }}>/10</span></span></td>
                        <td style={{ fontFamily: 'var(--font-mono)', fontSize: 12 }}>{(c.skills_match_score || 0).toFixed(1)}</td>
                        <td style={{ fontFamily: 'var(--font-mono)', fontSize: 12 }}>{(c.experience_score || 0).toFixed(1)}</td>
                        <td style={{ fontFamily: 'var(--font-mono)', fontSize: 12 }}>{(c.education_score || 0).toFixed(1)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}

            {candidates.length > 0 && (
              <div style={{ marginTop: 16, paddingTop: 16, borderTop: '1px solid var(--border)' }}>
                <div className="form-group">
                  <label>Decision Notes (optional)</label>
                  <textarea value={notes} onChange={e => setNotes(e.target.value)} placeholder="Reasoning for your selection..." rows={3} />
                </div>
                <div style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
                  <button className="btn btn-primary" onClick={handleSubmit} disabled={submitting || !selectedCandidate}>
                    {submitting ? 'Submitting...' : `Submit Decision${alternates.length > 0 ? ` (1 selected + ${alternates.length} alternate${alternates.length > 1 ? 's' : ''})` : ''}`}
                  </button>
                  <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>
                    {selectedCandidate ? `Selected: ${candidates.find(c => c.candidate_id === selectedCandidate)?.original_filename}` : 'No candidate selected yet'}
                  </span>
                </div>
              </div>
            )}
          </div>
        </>
      )}

      {toast && <div className={`toast ${toast.type}`}>{toast.msg}</div>}
    </div>
  );
}
